apiVersion: v1
kind: Service
metadata:
  name: opencanary
spec:
  selector:
    app: opencanary
  type: NodePort
  ports:
    - name: ftp
      port: 21
      targetPort: 21
      nodePort: 30021
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
